version: '3'

services:
  web:
    build: .
    container_name: django_container
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=codelap.settings


  nginx:
    image: nginx:alpine
    container_name: nginx_container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dev.codeleap.co.uk.crt:/etc/nginx/certs/dev.codeleap.co.uk.crt
      - ./dev.codeleap.co.uk.key:/etc/nginx/certs/dev.codeleap.co.uk.key
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - web
